services:
  mysql:
    image: mysql:8.0
    container_name: bilbase_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bilbase
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3310:3306"
    volumes:
      - bilbase_mysql_data:/var/lib/mysql
      - ../SQL_scripts:/docker-entrypoint-initdb.d
    command: --log-bin-trust-function-creators=1

volumes:
  bilbase_mysql_data:
