# MySQL
mysql.url=jdbc:mysql://localhost:3307/bilbase_projekt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
mysql.username=root
mysql.password=123456

# MongoDB
mongo.uri=mongodb://localhost:27017
mongo.database=bilbasen
