# MySQL
mysql.url=jdbc:mysql://localhost:3310/bilbase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
mysql.username=user
mysql.password=123456

# MongoDB
mongo.uri=mongodb://localhost:27017
mongo.database=bilbasen
