spring.data.mongodb.uri=mongodb://localhost:27018
spring.data.mongodb.database=bilbasen

# Fixes Pageable in Swagger UI ? renders explicit page/size/sort fields
springdoc.default-flat-param-object=true
